using UnityEngine;
using UnityEngine.InputSystem;
using System.Collections.Generic;

[RequireComponent(typeof(AudioSource))]
public class PlayerGrab : MonoBehaviour
{
    [Header("基本設定")]
    [SerializeField] private Vector2 grabOffset = new Vector2(0f, 0.7f);
    [SerializeField] private float throwForce = 7f;
    [SerializeField] private float smoothSpeed = 50f;
    [SerializeField] private LayerMask itemLayer;
    [SerializeField] private float maxGrabDistance = 2.0f;

    [Header("エイム矢印の設定")]
    [SerializeField] private Sprite arrowSprite;
    [SerializeField] private float arrowDistance = 1.5f;
    [SerializeField] private Vector3 arrowScale = new Vector3(0.25f, 0.25f, 1f);
    private GameObject generatedArrow;

    [Header("SE設定")]
    [SerializeField] private AudioSource audioSource;
    [SerializeField] private AudioClip grabSound;
    [SerializeField] private AudioClip throwSound;
    [Range(0f, 0.3f)][SerializeField] private float pitchRandomness = 0.1f;

    private GameObject grabbedObject;
    private Rigidbody2D grabbedRb;
    private Collider2D grabbedCol;
    private List<GameObject> canGrabItems = new List<GameObject>();

    private bool isAiming = false;
    private Vector2 aimDirection = Vector2.right;
    public bool IsAiming => isAiming;

    void Awake()
    {
        if (audioSource == null) audioSource = GetComponent<AudioSource>();
        audioSource.playOnAwake = false;
        audioSource.loop = false;

        if (arrowSprite != null)
        {
            generatedArrow = new GameObject("AimArrow_AutoGenerated");
            generatedArrow.transform.SetParent(transform);
            var sr = generatedArrow.AddComponent<SpriteRenderer>();
            sr.sprite = arrowSprite;
            sr.sortingOrder = 10;
            generatedArrow.transform.localScale = arrowScale;
            generatedArrow.SetActive(false);
        }
    }

    void Update()
    {
        HandleInput();

        // アイテムを持っているなら、毎フレーム位置を更新する
        if (grabbedObject != null)
        {
            FollowPlayer();
        }

        // エイム矢印の更新
        if (isAiming && generatedArrow != null)
        {
            UpdateArrowPositionAndRotation();
        }
    }

    private void HandleInput()
    {
        if (Gamepad.current == null && Keyboard.current == null) return;

        // 拾う：西ボタン(Gamepad) または 左クリック(Mouse)
        bool grabPressed = (Gamepad.current != null && Gamepad.current.buttonWest.wasPressedThisFrame) ||
                           (Mouse.current != null && Mouse.current.leftButton.wasPressedThisFrame);

        if (grabPressed && grabbedObject == null)
        {
            TryGrabNearestItem();
        }

        // 投げるための溜め：東ボタン(Gamepad) または 右クリック(Mouse)
        bool dropButtonHeld = (Gamepad.current != null && Gamepad.current.buttonEast.isPressed) ||
                              (Mouse.current != null && Mouse.current.rightButton.isPressed);

        bool dropButtonReleased = (Gamepad.current != null && Gamepad.current.buttonEast.wasReleasedThisFrame) ||
                                  (Mouse.current != null && Mouse.current.rightButton.wasReleasedThisFrame);

        if (grabbedObject != null)
        {
            if (dropButtonHeld)
            {
                if (!isAiming)
                {
                    isAiming = true;
                    if (generatedArrow != null) generatedArrow.SetActive(true);
                }
                UpdateAimDirection();
            }

            if (dropButtonReleased)
            {
                ThrowItem();
                isAiming = false;
                if (generatedArrow != null) generatedArrow.SetActive(false);
            }
        }
    }

    private void TryGrabNearestItem()
    {
        canGrabItems.RemoveAll(item => item == null);
        GameObject nearest = null;
        float minDist = maxGrabDistance;

        foreach (var item in canGrabItems)
        {
            float dist = Vector2.Distance(transform.position, item.transform.position);
            if (dist < minDist)
            {
                minDist = dist;
                nearest = item;
            }
        }

        if (nearest != null) GrabItem(nearest);
    }

    private void GrabItem(GameObject target)
    {
        grabbedObject = target;

        // 拾った瞬間、親子関係を一度解除（変な座標オフセットを防ぐ）
        grabbedObject.transform.SetParent(null);

        if (grabbedObject.TryGetComponent(out grabbedRb))
        {
            grabbedRb.bodyType = RigidbodyType2D.Kinematic; // 物理に邪魔させない
            grabbedRb.linearVelocity = Vector2.zero;
            grabbedRb.angularVelocity = 0f;
        }

        // プレイヤーとぶつからないようにコライダーを一時的にトリガー化
        if (grabbedObject.TryGetComponent(out grabbedCol))
        {
            grabbedCol.isTrigger = true;
        }

        PlayRandomPitchSE(grabSound);
    }

    private void ThrowItem()
    {
        GameObject itemToThrow = grabbedObject;
        Rigidbody2D rbToThrow = grabbedRb;
        Collider2D colToThrow = grabbedCol;

        grabbedObject = null;
        grabbedRb = null;
        grabbedCol = null;

        if (itemToThrow != null)
        {
            if (colToThrow != null) colToThrow.isTrigger = false; // 物理を戻す

            if (rbToThrow != null)
            {
                rbToThrow.bodyType = RigidbodyType2D.Dynamic;
                rbToThrow.linearVelocity = Vector2.zero;
                rbToThrow.AddForce(aimDirection * throwForce, ForceMode2D.Impulse);
            }
            PlayRandomPitchSE(throwSound);
        }
    }

    private void FollowPlayer()
    {
        // プレイヤーの向きに合わせて左右オフセットを調整
        Vector2 currentOffset = grabOffset;
        currentOffset.x *= Mathf.Sign(transform.localScale.x);

        Vector3 targetPosition = transform.position + (Vector3)currentOffset;

        // アイテムの位置を滑らかに更新（Update内で動かす）
        grabbedObject.transform.position = Vector3.Lerp(
            grabbedObject.transform.position,
            targetPosition,
            smoothSpeed * Time.deltaTime
        );
    }

    private void UpdateAimDirection()
    {
        if (Gamepad.current != null && Gamepad.current.leftStick.ReadValue().magnitude > 0.1f)
        {
            aimDirection = Gamepad.current.leftStick.ReadValue().normalized;
        }
        else if (Mouse.current != null)
        {
            Vector3 mousePos = Camera.main.ScreenToWorldPoint(Mouse.current.position.ReadValue());
            mousePos.z = 0;
            aimDirection = ((Vector2)mousePos - (Vector2)transform.position).normalized;
        }
    }

    private void UpdateArrowPositionAndRotation()
    {
        generatedArrow.transform.localPosition = (Vector3)(aimDirection * arrowDistance);
        float angle = Mathf.Atan2(aimDirection.y, aimDirection.x) * Mathf.Rad2Deg;
        generatedArrow.transform.rotation = Quaternion.Euler(0, 0, angle);
    }

    private void PlayRandomPitchSE(AudioClip clip)
    {
        if (clip == null || audioSource == null) return;
        audioSource.pitch = 1f + Random.Range(-pitchRandomness, pitchRandomness);
        audioSource.PlayOneShot(clip);
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (((1 << collision.gameObject.layer) & itemLayer) != 0)
        {
            if (!canGrabItems.Contains(collision.gameObject))
                canGrabItems.Add(collision.gameObject);
        }
    }

    private void OnTriggerExit2D(Collider2D collision)
    {
        if (canGrabItems.Contains(collision.gameObject))
        {
            canGrabItems.Remove(collision.gameObject);
        }
    }
}